Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2019-11, with the labels that each got.

#218 [VCCS-773] Update content
  Gemfile.lock
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/welcome/index.html.haml
  config/initializers/content_security_policy.rb
  package.json
  yarn.lock
Labels: documentation

#221 [VCCS-763] Clear checked la's if no la was selected
  .github/PULL_REQUEST_TEMPLATE
  app/controllers/air_zones_controller.rb
  app/controllers/application_controller.rb
  app/controllers/vehicle_checkers_controller.rb
Labels: bug

#222 [VCCS-773] Revert update content
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
Labels: documentation

#227 [NT] Small improvements
  .github/PULL_REQUEST_TEMPLATE
  Gemfile.lock
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  config/application.rb
  config/initializers/env_variables_checker.rb
  sonar-project.properties
  yarn.lock
Labels: improvement

#228 [CAZ-1443] Fix back button exempt page
  app/views/vehicle_checkers/cannot_determinate.html.haml
Labels: bug

#229 [CAZ-1492] Update ruby version to 2.6.5
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  README.md
  package.json
  yarn.lock
Labels: enhancement

#231 [VCCS-806] Update contact form
  app/controllers/contact_forms_controller.rb
  app/models/contact_form.rb
  app/services/sqs/base_message.rb
  app/views/contact_forms/form_input/_errored.html.haml
  app/views/contact_forms/form_input/_normal.html.haml
  config/initializers/content_security_policy.rb
  features/contact_form.feature
  features/step_definitions/contact_form_steps.rb
  spec/models/contact_form_spec.rb
  spec/requests/contact_forms_spec.rb
  spec/services/sqs/jaqu_message_spec.rb
  spec/services/sqs/user_message_spec.rb
  spec/support/shared_examples/sqs_email.rb
Labels: enhancement

#235 Add hidden legend to contact form
  app/views/air_zones/caz_selection.html.haml
  app/views/contact_forms/index.html.haml
Labels: enhancement

#236 [VCCS-815] Add privacy notice page
  app/controllers/privacy_notice_controller.rb
  app/views/layouts/_footer.html.haml
  app/views/privacy_notice/index.html.haml
  config/routes.rb
  features/privacy_notice.feature
  features/step_definitions/privacy_notice_steps.rb
  spec/requests/privacy_notice_spec.rb
Labels: enhancement

#238 [VCCS-821] Update cookies page
  app/views/cookies/_ga.html.haml
  app/views/cookies/_identify.html.haml
  app/views/cookies/_security.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/_table_head.html.haml
  app/views/cookies/index.html.haml
  app/views/privacy_notice/index.html.haml
  features/cookies.feature
Labels: enhancement

#239 Update ECS prod rollout step to draw from preprod
  .drone.yml
Labels: bug
