Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-11, with the labels that each got.

#624 Release v1.15.1 to staging
  .drone2.yml
  .project
  .rubocop.yml
  .ruby-version
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  .vscode/launch.json
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrapper/api_exception.rb
  app/api_wrapper/base_api.rb
  app/api_wrapper/compliance_checker_api.rb
  app/helpers/application_helper.rb
  app/javascript/styles/application.scss
  app/models/compliance_details.rb
  app/models/compliance_details_base.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/exemption.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/welcome/index.html.haml
  config/application.rb
  config/cucumber.yml
  config/initializers/content_security_policy.rb
  config/initializers/webpacker.rb
  features/support/helpers.rb
  features/support/mock_helpers.rb
  sonar-project.properties
  spec/models/compliance_details_base_spec.rb
  spec/models/compliance_details_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/models/vrn_form_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/parsed_reponse.rb
  spec/support/shared_examples/invalid_country_input.rb
  spec/support/shared_examples/invalid_vrn_input.rb
Labels: dont merge yet, release, release/v1.15.1

#628 Promote VCCS v1.15.1 to Production
  .drone2.yml
  .project
  .rubocop.yml
  .ruby-version
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  .vscode/launch.json
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrapper/api_exception.rb
  app/api_wrapper/base_api.rb
  app/api_wrapper/compliance_checker_api.rb
  app/helpers/application_helper.rb
  app/javascript/styles/application.scss
  app/models/compliance_details.rb
  app/models/compliance_details_base.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/exemption.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/welcome/index.html.haml
  config/application.rb
  config/cucumber.yml
  config/initializers/content_security_policy.rb
  config/initializers/webpacker.rb
  features/support/helpers.rb
  features/support/mock_helpers.rb
  sonar-project.properties
  spec/models/compliance_details_base_spec.rb
  spec/models/compliance_details_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/models/vrn_form_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/parsed_reponse.rb
  spec/support/shared_examples/invalid_country_input.rb
  spec/support/shared_examples/invalid_vrn_input.rb
Labels: VCCS v1.15.1, dont merge yet, release

#634 [CAZB-3528] Update the privacy policy page
  .gitignore
  Gemfile.lock
  app/views/static_pages/privacy_notice.html.haml
Labels: improvement

#642 Promote VCCS v1.16.2 UI to Production
  .gitignore
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrapper/base_api.rb
  app/models/compliance_details.rb
  app/models/vehicle_details.rb
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  config/locales/en.yml
  features/vehicle_checker.feature
  package.json
  spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
  spec/api_wrappers/compliance_checker_api/vehicle_details_spec.rb
  spec/fixtures/files/vehicle_details_response.json
  spec/i18n_spec.rb
  spec/models/vehicle_details_spec.rb
  spec/models/vrn_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  spec/spec_helper.rb
  spec/support/shared_examples/invalid_country_input.rb
  spec/support/shared_examples/invalid_vrn_input.rb
  yarn.lock
Labels: VCCS v1.16.2, release
