Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-08, with the labels that each got.

#536 [CAZB-2505] Fix typos and update devs and test gems
  .drone.yml
  .drone2.yml
  .rubocop.yml
  Gemfile.lock
  app/views/air_zones/compliance.html.haml
  config/initializers/filter_parameter_logging.rb
  config/puma.rb
  package.json
  yarn.lock
Labels: bug

#540 [CAZB-1197] Completely remove contact form files and SQS services
  .env.example
  Gemfile
  Gemfile.lock
  app/controllers/concerns/.keep
  app/models/concerns/.keep
  app/models/contact_form.rb
  app/services/sqs/base_message.rb
  app/services/sqs/jaqu_message.rb
  app/services/sqs/user_message.rb
  config/initializers/aws_sqs.rb
  config/webpack/environment.js
  features/step_definitions/vehicle_checker_steps.rb
  features/support/mock_helpers.rb
  lib/tasks/.keep
  package.json
  spec/models/contact_form_spec.rb
  spec/services/sqs/jaqu_message_spec.rb
  spec/services/sqs/user_message_spec.rb
  spec/support/shared_examples/sqs_email.rb
  yarn.lock
Labels: improvement

#547 Promote release/v1.11.1 to Pre-prod
  .drone.yml
  .drone2.yml
  .rubocop.yml
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/models/compliance.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  config/initializers/filter_parameter_logging.rb
  config/puma.rb
  features/vehicle_checker.feature
  package.json
  spec/fixtures/files/non_chargeable_vehicle_compliance_response.json
  spec/models/compliance_spec.rb
  spec/models/non_uk_compliant_vehicle_details_spec.rb
  spec/rails_helper.rb
  spec/requests/air_zones/compliance_spec.rb
  spec/requests/vehicle_checker_controller/confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
  spec/support/fixtures_helpers.rb
  yarn.lock
Labels: release, release/v1.11.1

#550 Promote release v1.11.1 to Production
  .drone.yml
  .drone2.yml
  .rubocop.yml
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/models/compliance.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  config/initializers/filter_parameter_logging.rb
  config/puma.rb
  features/vehicle_checker.feature
  package.json
  spec/fixtures/files/non_chargeable_vehicle_compliance_response.json
  spec/models/compliance_spec.rb
  spec/models/non_uk_compliant_vehicle_details_spec.rb
  spec/rails_helper.rb
  spec/requests/air_zones/compliance_spec.rb
  spec/requests/vehicle_checker_controller/confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
  spec/support/fixtures_helpers.rb
  yarn.lock
Labels: release, release/v1.11.1
