Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-01, with the labels that each got.

#276 [CAZB-294] Fix back button on the Contact Us page
  Gemfile
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/controllers/contact_forms_controller.rb
  app/views/air_zones/caz_selection.html.haml
  app/views/vehicle_checkers/cannot_determinate.html.haml
  config/routes.rb
  features/air_zones.feature
  features/step_definitions/helper_steps.rb
  package.json
  spec/models/caz_spec.rb
  spec/rails_helper.rb
  spec/requests/air_zones/compliance_spec.rb
  spec/requests/air_zones/submit_caz_selection_spec.rb
  spec/requests/contact_forms_spec.rb
  spec/services/sqs/jaqu_message_spec.rb
  spec/services/sqs/user_message_spec.rb
  yarn.lock
Labels: bug

#278 [CAZB-290, 292, 295, 296, 301] Update content
  Gemfile.lock
  app/helpers/application_helper.rb
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/common/_external_link.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_feedback_section.html.haml
  app/views/privacy_notice/index.html.haml
  app/views/vehicle_checkers/cannot_determinate.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/welcome/index.html.haml
  features/air_zones.feature
  features/vehicle_checker.feature
  yarn.lock
Labels: enhancement

#279 [CAZB-293] Add accessibility statement page
  .rubocop.yml
  app/controllers/accessibility_controller.rb
  app/views/accessibility/index.html.haml
  app/views/layouts/_footer.html.haml
  config/routes.rb
  features/accessibility.feature
  features/cookies.feature
  features/privacy_notice.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/privacy_notice_steps.rb
  spec/requests/accessibility_spec.rb
Labels: enhancement

#281 [NT] Refactor determinate_back_path method in contact forms controller
  app/controllers/contact_forms_controller.rb
Labels: improvement

#282 [CAZB-293] Update accessibility statement page
  app/views/accessibility/index.html.haml
Labels: enhancement

#286 [CAZB-301] Change url path for cannot determine page
  .drone.yml
  Gemfile.lock
  app/controllers/air_zones_controller.rb
  app/controllers/contact_forms_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/views/vehicle_checkers/cannot_determine.html.haml
  config/routes.rb
  features/step_definitions/vehicle_checker_steps.rb
  spec/requests/air_zones/caz_selection_spec.rb
  spec/requests/air_zones/compliance_spec.rb
  spec/requests/vehicle_checker_controller/cannot_determinate_spec.rb
  yarn.lock
Labels: enhancement

#277 [CAZB-88] Update compliance page
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/views/air_zones/compliance.html.haml
  spec/models/compliance_details_spec.rb
Labels: enhancement

#287 [NT] Use yarn exclude 961 unless fix will be released
  .drone.yml
  package.json
  yarn.lock
Labels: bug

#284 [WIP][VCCS-922] Add taxi or phv checkbox
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/controllers/application_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/models/compliance.rb
  app/models/vehicle_details.rb
  app/views/vehicle_checkers/_taxi_or_phv_checkbox.html.haml
  app/views/vehicle_checkers/country_input/_errored.html.haml
  app/views/vehicle_checkers/country_input/_normal.html.haml
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
  spec/models/compliance_spec.rb
  yarn.lock
Labels: enhancement

#294 [NT] Update ruby alpine version to fix ci failing
  Dockerfile.test
  yarn.lock
Labels: bug

#296 [NT] Update ruby alpine version in Dockerfile.build
  Dockerfile.build
Labels: bug

#298 Release/v1.1.0
  .drone.yml
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/accessibility_controller.rb
  app/controllers/air_zones_controller.rb
  app/controllers/contact_forms_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/helpers/application_helper.rb
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/common/_external_link.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_feedback_section.html.haml
  app/views/layouts/_footer.html.haml
  app/views/privacy_notice/index.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/welcome/index.html.haml
  config/routes.rb
  features/accessibility.feature
  features/air_zones.feature
  features/cookies.feature
  features/privacy_notice.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/privacy_notice_steps.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  jmeter/valid_vehicle_compliance.jmx
  package.json
  spec/models/caz_spec.rb
  spec/models/compliance_details_spec.rb
  spec/rails_helper.rb
  spec/requests/accessibility_spec.rb
  spec/requests/air_zones/caz_selection_spec.rb
  spec/requests/air_zones/compliance_spec.rb
  spec/requests/air_zones/submit_caz_selection_spec.rb
  spec/requests/contact_forms_spec.rb
  spec/requests/vehicle_checker_controller/cannot_determinate_spec.rb
  spec/services/sqs/jaqu_message_spec.rb
  spec/services/sqs/user_message_spec.rb
  yarn.lock
Labels: release, v1.1.0

#297 [CAZB-28, CAZB-31] Update cookies banner to allow use keyboard focus
  Gemfile.lock
  app/views/layouts/_cookies_banner.haml
Labels: enhancement

#300 [NT] Fix end to end tests
  app/views/air_zones/compliance.html.haml
Labels: bug

#301 Promote release v1.1.0 to Production
  .drone.yml
  .rubocop.yml
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/accessibility_controller.rb
  app/controllers/air_zones_controller.rb
  app/controllers/contact_forms_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/helpers/application_helper.rb
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/common/_external_link.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_feedback_section.html.haml
  app/views/layouts/_footer.html.haml
  app/views/privacy_notice/index.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/welcome/index.html.haml
  config/routes.rb
  features/accessibility.feature
  features/air_zones.feature
  features/cookies.feature
  features/privacy_notice.feature
  features/step_definitions/cookies_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/privacy_notice_steps.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  jmeter/valid_vehicle_compliance.jmx
  package.json
  spec/models/caz_spec.rb
  spec/models/compliance_details_spec.rb
  spec/rails_helper.rb
  spec/requests/accessibility_spec.rb
  spec/requests/air_zones/caz_selection_spec.rb
  spec/requests/air_zones/compliance_spec.rb
  spec/requests/air_zones/submit_caz_selection_spec.rb
  spec/requests/contact_forms_spec.rb
  spec/requests/vehicle_checker_controller/cannot_determinate_spec.rb
  spec/services/sqs/jaqu_message_spec.rb
  spec/services/sqs/user_message_spec.rb
  yarn.lock
Labels: release, v1.1.0

#299 [CAZB-355] Update compliance page
  app/views/air_zones/compliance.html.haml
Labels: enhancement

#290 [CAZB-297] Move taxi or phv checkbox to confirm details page
  app/controllers/air_zones_controller.rb
  app/controllers/application_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/models/confirm_details_form.rb
  app/models/confirmation_form.rb
  app/models/vehicle_details.rb
  app/views/vehicle_checkers/_taxi_or_phv_checkbox.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/country_input/_errored.html.haml
  app/views/vehicle_checkers/country_input/_normal.html.haml
  app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
  config/routes.rb
  features/air_zones.feature
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  spec/models/confirm_details_form_spec.rb
  spec/models/confirmation_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/user_confirm_details_spec.rb
Labels: enhancement

#302 [NT] Update github pr template
  .github/PULL_REQUEST_TEMPLATE
Labels: enhancement

#303 [NT] Update drone.yml (removed `exclude 961` from yarn audit)
  .drone.yml
Labels: improvement

#304 [NT] Fix pa11y tests
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/welcome/index.html.haml
  pa11y/.pa11yci.conf.js
Labels: enhancement

#306 [NT] Update pa11y test
  pa11y/.pa11yci.conf.js
Labels: bug

#305 [CAZB-373] Update welcome page content
  Gemfile.lock
  app/views/welcome/index.html.haml
  package.json
  yarn.lock
Labels: enhancement

#308 [CAZB-293] Fix typo on accessibility page
  app/views/accessibility/index.html.haml
Labels: bug

#312 [CAZB-341, CAZB-335, CAZB-293] Update content
  .drone.yml
  app/models/confirm_details_form.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/compliance.html.haml
  config/locales/en.yml
  features/vehicle_checker.feature
  spec/models/confirm_details_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
Labels: bug

#314 Release/v1.1.1
  .drone.yml
  app/models/confirm_details_form.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/compliance.html.haml
  config/locales/en.yml
  features/vehicle_checker.feature
  spec/models/confirm_details_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
Labels: release, v1.1.1

#321 Add drone steps for new ST environment
  .drone.yml
Labels: enhancement

#323 [CAZB-423] Fix zap warnings
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/_google_analytics.html.haml
  config/initializers/application_controller_renderer.rb
  config/initializers/check_request_format.rb
  config/routes.rb
  sonar-project.properties
  spec/requests/application_controller_spec.rb
  zap.conf
Labels: bug

#322 Promote v1.1.1 to Production
  .drone.yml
  .github/PULL_REQUEST_TEMPLATE
  Dockerfile.build
  Dockerfile.test
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/controllers/application_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/models/compliance.rb
  app/models/confirm_details_base_form.rb
  app/models/confirm_details_form.rb
  app/models/confirm_details_taxi_form.rb
  app/models/confirmation_form.rb
  app/models/vehicle_details.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/contact_forms/index.html.haml
  app/views/contact_forms/result.html.haml
  app/views/cookies/index.html.haml
  app/views/errors/internal_server_error.html.haml
  app/views/errors/not_found.html.haml
  app/views/errors/service_unavailable.html.haml
  app/views/layouts/_cookies_banner.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/exemption.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
  app/views/welcome/index.html.haml
  config/locales/en.yml
  config/routes.rb
  features/air_zones.feature
  features/step_definitions/vehicle_checker_steps.rb
  features/support/mock_helpers.rb
  features/vehicle_checker.feature
  jmeter/manual-load-test/vccs-ve-concurrency-test.jmx
  jmeter/valid_vehicle_compliance.jmx
  pa11y/.pa11yci.conf.js
  package.json
  spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/user_confirm_details_spec.rb
  spec/support/shared_examples/invalid_country_input.rb
  yarn.lock
Labels: release, v1.1.1

#326 [CAZB-423] Fix OWASP ZAP warning
  config/initializers/check_request_format.rb
  config/routes.rb
  spec/requests/application_controller_spec.rb
  zap.conf
Labels: bug

#328 [NT] Fix sonar-scanner parse error and update sonar config
  app/views/layouts/_google_analytics.html.erb
  app/views/layouts/_google_analytics.html.haml
  config/initializers/application_controller_renderer.rb
  sonar-project.properties
  spec/requests/application_controller_spec.rb
Labels: bug

#329 [CAZB-451] Hide taxi button for n1, n2, n3 and m3 vehicles types
  app/models/vehicle_details.rb
  app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
  features/step_definitions/helper_steps.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  spec/models/vehicle_details_spec.rb
Labels: improvement

#331 [NT] Add basic auth to pa11y tests
  .drone.yml
Labels: improvement
