Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-03, with the labels that each got.

#367 [NT] Update puma version to fix vulnerability warning
  Gemfile.lock
  package.json
  yarn.lock
Labels: improvement

#369 [CAZB-454] Content change to VCCS Cookie Policy
  app/helpers/application_helper.rb
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_header.html.haml
  config/application.rb
  spec/models/vehicle_details_spec.rb
Labels: improvement

#372 [CAZB-454] `Accept all cookies` button enabled GA cookies by default
  app/views/layouts/_cookie_control.html.erb
Labels: improvement

#371 Promote release v1.7.0 to staging
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/views/privacy_notice/index.html.haml
  pa11y/.pa11yci.conf.js
  package.json
  yarn.lock
  zap.conf
Labels: dont merge yet, release, v1.7.0

#373 Promote v1.7.0 to Production
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  app/views/privacy_notice/index.html.haml
  pa11y/.pa11yci.conf.js
  package.json
  yarn.lock
  zap.conf
Labels: release, v1.7.0

#376 [CAZB-738] Hide Control Cookie buttons and add `Save and close` button
  app/views/layouts/_cookie_control.html.erb
  yarn.lock
Labels: improvement

#377 [CAZB-738] Remove Control Cookie buttons from DOM
  app/views/layouts/_cookie_control.html.erb
Labels: improvement

#386 [CAZSM-8] Add debug log level to prod
  config/environments/production.rb
Labels: bug

#387 [NT] Show custom logs in production
  config/environments/production.rb
Labels: bug

#383 Promote v1.7.1 to pre-production
  .env.example
  .rubocop.yml
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookieControl.js
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/services/sqs/base_message.rb
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  app/views/privacy_notice/index.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/log_format.rb
  pa11y/.pa11yci.conf.js
  spec/models/vehicle_details_spec.rb
Labels: release, v1.7.1

#390 Promote v1.7.1 to Production
  .env.example
  .rubocop.yml
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/helpers/application_helper.rb
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookieControl.js
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/services/sqs/base_message.rb
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/_ga.html.haml
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/_session.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.haml
  app/views/layouts/_header.html.haml
  app/views/layouts/application.html.haml
  app/views/privacy_notice/index.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/content_security_policy.rb
  config/initializers/filter_parameter_logging.rb
  config/log_format.rb
  pa11y/.pa11yci.conf.js
  spec/models/vehicle_details_spec.rb
Labels: release, v1.7.1

#393 [CAZB-723] Update enter details page
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/vrn_input/_errored.html.haml
  app/views/vehicle_checkers/vrn_input/_normal.html.haml
  features/step_definitions/path_expectations.rb
  features/vehicle_checker.feature
Labels: improvement

#394 [CAZB-764, CAZB-765, CAZB-766] Update content
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  config/locales/en.yml
Labels: improvement

#395 [CAZB-765] Fix error message on enter details page
  config/locales/en.yml
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
Labels: bug

#399 [NT] Ignore security warning for yarn audit
  .drone.yml
Labels: bug

#400 Update rails version to fix XSS vulnerability in ActionView
  Gemfile
  Gemfile.lock
Labels: dependencies
