Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-10, with the labels that each got.

#601 [CAZB-3297] Addition of the charging dates on the compliance page
  .rubocop.yml
  .ruby-version
  Dockerfile.build
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/api_wrapper/api_exception.rb
  app/api_wrapper/base_api.rb
  app/api_wrapper/compliance_checker_api.rb
  app/models/compliance_details.rb
  app/models/compliance_details_base.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  config/application.rb
  config/cucumber.yml
  config/initializers/content_security_policy.rb
  config/initializers/webpacker.rb
  features/support/helpers.rb
  features/support/mock_helpers.rb
  sonar-project.properties
  spec/models/compliance_details_base_spec.rb
  spec/models/compliance_details_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/models/vrn_form_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/parsed_reponse.rb
  spec/support/shared_examples/invalid_country_input.rb
  spec/support/shared_examples/invalid_vrn_input.rb
Labels: improvement, ruby

#604 [CAZB-3323] Fix Back link layout on printed Compliance page
  .drone2.yml
  app/helpers/application_helper.rb
  app/javascript/styles/application.scss
  app/views/air_zones/compliance.html.haml
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/cookies.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/exemption.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
Labels: bug

#602 Promote VCCS v1.14.1 to Pre-Prod
  .drone2.yml
  .project
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  .vscode/launch.json
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/vehicle_checkers/vrn_input/_errored.html.haml
  app/views/vehicle_checkers/vrn_input/_normal.html.haml
Labels: VCCS v1.14.1, do not merge, release

#607 Remove full stop from CAZ link
  app/views/air_zones/compliance.html.haml
  app/views/welcome/index.html.haml
Labels: bug

#612 Promote VCCS v1.14.2 to Pre-Production
  app/views/air_zones/compliance.html.haml
Labels: VCCS v1.14.2, dont merge yet, release

#615 [CAZB-3360] Update content on the confirm vehicle details page
  .gitignore
  Dockerfile.test
  Gemfile.lock
  app/models/compliance_details.rb
  app/models/vehicle_details.rb
  app/views/vehicle_checkers/confirm_details.html.haml
  features/vehicle_checker.feature
  package.json
  spec/api_wrappers/compliance_checker_api/vehicle_details_spec.rb
  spec/fixtures/files/vehicle_details_response.json
  spec/models/vehicle_details_spec.rb
  spec/models/vrn_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  yarn.lock
Labels: improvement

#614 Promote VCCS v1.14.3 to Production
  .drone2.yml
  .project
  .settings/.jsdtscope
  .settings/org.eclipse.wst.jsdt.ui.superType.container
  .settings/org.eclipse.wst.jsdt.ui.superType.name
  .vscode/launch.json
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/models/non_uk_compliant_vehicle_details.rb
  app/views/air_zones/compliance.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/number_not_found.html.haml
  app/views/vehicle_checkers/vrn_input/_errored.html.haml
  app/views/vehicle_checkers/vrn_input/_normal.html.haml
Labels: VCCS v1.14.3, dont merge yet, release
