Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-02, with the labels that each got.

#333 [CAZB-435] Update content
  app/views/layouts/_header.html.haml
  app/views/privacy_notice/index.html.haml
  app/views/welcome/index.html.haml
  features/privacy_notice.feature
Labels: improvement

#340 Promote v1.1.2 to Production
  app/controllers/vehicle_checkers_controller.rb
  app/models/confirm_details_base_form.rb
  app/models/vehicle_details.rb
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
  features/step_definitions/helper_steps.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  pa11y/.pa11yci.conf.js
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/models/vehicle_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
Labels: release, v1.1.2

#342 Promote Release v1.4.1 to Staging
  app/views/accessibility/index.html.haml
Labels: do not merge

#346 [CAZB-499] Update compliance page
  app/views/air_zones/compliance.html.haml
Labels: improvement

#347 [NT] Remove sass-rails and small refactoring
  .drone.yml
  .env.test
  Dockerfile.test
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  config/initializers/aws_sqs.rb
  package.json
  yarn.lock
Labels: improvement

#348 [CAZB-474] Update compliance page
  app/views/air_zones/compliance.html.haml
Labels: improvement

#349 [CAZB-521] Update contact form page
  app/views/contact_forms/index.html.haml
Labels: improvement

#350 [NT] Refactoring drone.yml
  .drone.yml
Labels: improvement

#352 [CAZB-521] Update contact form
  app/views/contact_forms/index.html.haml
Labels: improvement

#361 [CAZB-474] Add control cookie component
  .env.example
  .rubocop.yml
  Gemfile.lock
  app/javascript/packs/application.js
  app/javascript/packs/google_analytics.js
  app/javascript/src/cookiesBanner/init.js
  app/javascript/src/cookiesBanner/styles.scss
  app/javascript/styles/application.scss
  app/javascript/styles/cookie_control.scss
  app/views/cookies/_seen_message.html.haml
  app/views/cookies/index.html.haml
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/_cookies_banner.haml
  app/views/layouts/_google_analytics.html.haml
  app/views/layouts/application.html.haml
  config/initializers/content_security_policy.rb
Labels: enhancement

#362 [CAZB-585] Update cookies page
  app/views/cookies/_cookie_control.html.haml
  app/views/cookies/index.html.haml
Labels: improvement

#363 [CAZB-614] Fix accessibility tests and zap tests
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/application.css
  pa11y/.pa11yci.conf.js
  package.json
  yarn.lock
  zap.conf
Labels: bug

#364 [CAZB-614] Fix accessibility tests and zap tests
  pa11y/.pa11yci.conf.js
Labels: bug

#365 [CAZB-614] Fix accessibility tests and zap tests
  pa11y/.pa11yci.conf.js
Labels: bug
