Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-04, with the labels that each got.

#404 Add drone configuration for UAT environment
  .drone.yml
Labels: enhancement

#405 [CAZB-27] Add table header to the vehicle details page
  app/javascript/styles/application.scss
  app/views/vehicle_checkers/confirm_details.html.haml
Labels: improvement

#411 [CAZB-27] Update table header on the vehicle details page
  app/views/vehicle_checkers/confirm_details.html.haml
Labels: improvement

#414 Promote release v1.8.1 to Production
  .drone.yml
  Gemfile
  Gemfile.lock
  app/views/air_zones/compliance.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/welcome/index.html.haml
  yarn.lock
Labels: VCCS v1.8.1, release

#422 [CAZB-1096] New Compliance page
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/moj.js
  app/javascript/styles/application.scss
  app/models/caz.rb
  app/models/compliance.rb
  app/views/air_zones/compliance.html.haml
  config/webpack/environment.js
  features/air_zones.feature
  features/step_definitions/air_zones_steps.rb
  features/step_definitions/helper_steps.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/step_definitions/welcome_steps.rb
  features/support/mock_helpers.rb
  features/vehicle_checker.feature
  package.json
  spec/api_wrappers/compliance_checker_api/clean_air_zones_spec.rb
  spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
  spec/fixtures/files/vehicle_compliance_response.json
  spec/models/caz_spec.rb
  spec/models/compliance_spec.rb
  yarn.lock
Labels: improvement

#428 Staging promote v1.9.1
  .drone.yml
  Gemfile
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/models/vehicle_details.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/vrn_input/_errored.html.haml
  app/views/vehicle_checkers/vrn_input/_normal.html.haml
  app/views/welcome/index.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/filter_parameter_logging.rb
  config/locales/en.yml
  config/log_format.rb
  features/air_zones.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/path_expectations.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  lib/custom_logger.rb
  pa11y/.pa11yci.conf.js
  spec/fixtures/files/vehicle_compliance_response.json
  spec/models/compliance_details_spec.rb
Labels: release
