Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2020-05, with the labels that each got.

#431 Promote v1.9.1 to Production
  .drone.yml
  Gemfile
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/models/compliance.rb
  app/models/compliance_details.rb
  app/models/vehicle_details.rb
  app/views/accessibility/index.html.haml
  app/views/air_zones/caz_selection.html.haml
  app/views/air_zones/compliance.html.haml
  app/views/vehicle_checkers/cannot_determine.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/vrn_input/_errored.html.haml
  app/views/vehicle_checkers/vrn_input/_normal.html.haml
  app/views/welcome/index.html.haml
  config/application.rb
  config/environments/production.rb
  config/initializers/filter_parameter_logging.rb
  config/locales/en.yml
  config/log_format.rb
  features/air_zones.feature
  features/step_definitions/helper_steps.rb
  features/step_definitions/path_expectations.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  lib/custom_logger.rb
  pa11y/.pa11yci.conf.js
  spec/fixtures/files/vehicle_compliance_response.json
  spec/models/compliance_details_spec.rb
Labels: VCCS v1.9.1, release

#434 [CAZB-475] Shows Taxi Radio button only for M1/M2 Vehicle Type Approvals
  app/models/vehicle_details.rb
  features/air_zones.feature
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  spec/fixtures/files/vehicle_details_response.json
  spec/models/vehicle_details_spec.rb
Labels: bug

#436 [CAZB-1302] Update plate number with a plate number form api response
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/models/vehicle_details.rb
  app/services/sqs/base_message.rb
  config/environments/production.rb
  features/step_definitions/vehicle_checker_steps.rb
  features/support/mock_helpers.rb
  spec/api_wrappers/compliance_checker_api/vehicle_details_spec.rb
  spec/fixtures/files/vehicle_details_response.json
  spec/models/vehicle_details_spec.rb
  spec/requests/vehicle_checker_controller/confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
Labels: improvement

#437 Add overflow scroll to compliance page table for mobile views
  app/javascript/styles/application.scss
  app/views/air_zones/compliance.html.haml
Labels: bug

#441 [CAZB-1400] Add C4 Level 4
  .gitignore
  doc/C4_Level_4.png
  doc/C4_Level_4.uml
Labels: improvement

#446 Fix loading fonts
  app/controllers/application_controller.rb
  config/initializers/check_request_format.rb
  config/initializers/content_security_policy.rb
  config/webpack/environment.js
Labels: bug

#447 [CAZB-1029] Update CookieControl to version 9
  .drone.yml
  app/javascript/styles/cookie_control.scss
  app/views/layouts/_cookie_control.html.erb
  app/views/layouts/application.html.haml
  package.json
  yarn.lock
Labels: improvement

#448 Add 'text/javascript' type to Control Cookie script
  app/views/layouts/application.html.haml
Labels: dependencies
