Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2021-04, with the labels that each got.

#730 [CAZB-4239] Refactor validating vrn to be consistent with payments ui
  app/controllers/vehicle_checkers_controller.rb
  app/models/vrn_form.rb
Labels: improvement

#725 Promote VCCS v2.1.0 to Pre-Production
  .rubocop.yml
  app/models/vrn_form.rb
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/welcome/index.html.haml
  config/environments/production.rb
  spec/fixtures/files/caz_list_response.json
  spec/fixtures/files/vehicle_compliance_response.json
  spec/models/compliance_details_base_spec.rb
Labels: VCCS v2.1.0, release

#735 Promote VCCS v2.1.1 to Production
  .rubocop.yml
  app/models/vrn_form.rb
  app/views/static_pages/accessibility_statement.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/welcome/index.html.haml
  config/environments/production.rb
  spec/fixtures/files/caz_list_response.json
  spec/fixtures/files/vehicle_compliance_response.json
  spec/models/compliance_details_base_spec.rb
Labels: VCCS v2.1.1, release

#739 [CAZB-4640] Update content to data message in VCCS results page
  app/views/air_zones/compliance.html.haml
Labels: improvement
