Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2021-03, with the labels that each got.

#700 [CAZB-4123] Amend text on Incorrect details page
  Gemfile
  Gemfile.lock
  app/views/vehicle_checkers/incorrect_details.html.haml
  config/database.yml
  config/environments/production.rb
  db/seeds.rb
  package.json
  yarn.lock
Labels: improvement

#702 [CAZB-4123] Fix accessibility test
  pa11y/.pa11yci.conf.js
Labels: bug

#705 Promote VCCS v2.0.0 to Pre-Production
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/air_zones_controller.rb
  app/javascript/packs/application.js
  app/javascript/src/backLink.js
  app/models/compliance.rb
  app/models/compliance_details_base.rb
  app/views/air_zones/compliance.html.haml
  app/views/common/_js_back_link.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  config/application.rb
  config/database.yml
  config/environments/production.rb
  db/seeds.rb
  features/air_zones.feature
  features/step_definitions/helper_steps.rb
  jmeter/manual-load-test/vccs-concurrency-test.jmx
  jmeter/valid_vehicle_compliance.jmx
  pa11y/.pa11yci.conf.js
  package.json
  spec/models/compliance_details_base_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/vrn_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
  spec/spec_helper.rb
  yarn.lock
Labels: VCCS v2.0.0, release

#710 Promote VCCS v2.0.1 to Pre-Prod
  app/views/air_zones/compliance.html.haml
Labels: VCCS v2.0.0, VCCS v2.0.1, release

#711 Promote VCCS v2.0.1 to Production
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/air_zones_controller.rb
  app/javascript/packs/application.js
  app/javascript/src/backLink.js
  app/models/compliance.rb
  app/models/compliance_details_base.rb
  app/views/air_zones/compliance.html.haml
  app/views/common/_js_back_link.html.haml
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
  app/views/vehicle_checkers/incorrect_details.html.haml
  app/views/vehicle_checkers/non_uk.html.haml
  config/application.rb
  config/database.yml
  config/environments/production.rb
  db/seeds.rb
  features/air_zones.feature
  features/step_definitions/helper_steps.rb
  jmeter/manual-load-test/vccs-concurrency-test.jmx
  jmeter/valid_vehicle_compliance.jmx
  pa11y/.pa11yci.conf.js
  package.json
  spec/models/compliance_details_base_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/vrn_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
  spec/spec_helper.rb
  yarn.lock
Labels: VCCS v2.0.1, release

#712 [CAZB-2084] Update accessibility policy content
  app/views/static_pages/accessibility_statement.html.haml
Labels: improvement

#718 [CAZB-3002] Disable cache on enter details page
  .rubocop.yml
  app/controllers/application_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/models/vrn_form.rb
Labels: bug
