Repository InformedSolutions/JAQU-CAZ-Vehicle-Compliance-Checker-Web, pull requests merged in 2021-02, with the labels that each got.

#669 [CAZB-3881] Fix back button flow on compliance page
  app/controllers/vehicle_checkers_controller.rb
  app/views/air_zones/compliance.html.haml
  features/vehicle_checker.feature
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
Labels: bug

#670 [CAZB-3881] Fix back button flow on incorrect vehicle details page
  app/views/vehicle_checkers/incorrect_details.html.haml
  features/vehicle_checker.feature
Labels: bug

#668 Promote VCCS v1.17.3 to Pre-Prod
  app/views/static_pages/privacy_notice.html.haml
Labels: VCCS v1.17.3, release

#672 [CAZB-4063] Migrate pipeline to Terraform v0.12.23
  .drone2.yml
Labels: bug

#673 Promote VCCS v1.17.3 to Production
  Gemfile.lock
  app/api_wrapper/base_api.rb
  app/views/static_pages/privacy_notice.html.haml
  app/views/vehicle_checkers/exemption.html.haml
  features/privacy_notice.feature
  package.json
  yarn.lock
Labels: VCCS v1.17.3, release

#674 Promote release v1.17.4 to pre-production
  .drone2.yml
Labels: release, release/v1.17.4

#676 [CAZB-4082] Remove self-declaration Taxi checkbox
  Gemfile.lock
  app/api_wrapper/compliance_checker_api.rb
  app/controllers/air_zones_controller.rb
  app/controllers/application_controller.rb
  app/controllers/vehicle_checkers_controller.rb
  app/models/compliance.rb
  app/models/confirm_details_base_form.rb
  app/models/confirm_details_form.rb
  app/models/confirm_details_taxi_form.rb
  app/models/vehicle_details.rb
  app/views/vehicle_checkers/confirm_details.html.haml
  app/views/vehicle_checkers/confirm_details/_radio_buttons.html.haml
  app/views/vehicle_checkers/confirm_uk_details.html.haml
  app/views/vehicle_checkers/taxi_or_phv_input/_radio_buttons.html.haml
  config/locales/en.yml
  features/air_zones.feature
  features/step_definitions/vehicle_checker_steps.rb
  features/vehicle_checker.feature
  package.json
  spec/api_wrappers/compliance_checker_api/vehicle_compliance_spec.rb
  spec/models/compliance_spec.rb
  spec/models/confirm_details_form_spec.rb
  spec/models/confirm_details_taxi_form_spec.rb
  spec/models/vehicle_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_details_spec.rb
  spec/requests/vehicle_checker_controller/submit_confirm_uk_details_spec.rb
  yarn.lock
Labels: improvement

#677 [CAZB-4082] Fix deploy
  package.json
  yarn.lock
Labels: bug

#679 Promote VCCS v1.17.4 to Production
  .drone2.yml
Labels: VCCS v1.17.4, release

#680 [CAZB-4055] Amend data message in results page
  .rubocop.yml
  Gemfile.lock
  app/views/air_zones/compliance.html.haml
  package.json
  spec/models/confirm_details_form_spec.rb
  spec/models/vrn_form_spec.rb
  spec/requests/vehicle_checker_controller/submit_details_spec.rb
  spec/spec_helper.rb
  yarn.lock
Labels: improvement

#681 [CAZB-4097] Update back button to JS on enter details page
  app/javascript/packs/application.js
  app/javascript/src/backLink.js
  app/views/common/_js_back_link.html.haml
  app/views/vehicle_checkers/enter_details.html.haml
Labels: improvement

#683 [CAZB-3953] Update results page to include link to payments
  app/models/compliance_details_base.rb
  app/views/air_zones/compliance.html.haml
  config/application.rb
  spec/models/compliance_details_base_spec.rb
Labels: improvement

#685 [CAZB-3953] Update results page to include link to payments
  config/application.rb
Labels: improvement

#687 [CAZB-2875] Change `drive` to `drove` on non-uk page
  app/views/vehicle_checkers/non_uk.html.haml
Labels: improvement

#690 [CAZB-3953] Update results page to include link to payments
  app/controllers/air_zones_controller.rb
  app/models/compliance.rb
  app/models/compliance_details_base.rb
  app/views/air_zones/compliance.html.haml
  features/air_zones.feature
  features/step_definitions/helper_steps.rb
  spec/models/compliance_spec.rb
Labels: improvement

#694 [CAZB-3953] Update results page to include dynamic links
  app/models/compliance_details_base.rb
  features/air_zones.feature
  spec/models/compliance_details_base_spec.rb
Labels: improvement
